### PR TITLE
DRAFT Feature/operator sdk v1.2

### PR DESCRIPTION
**Pull request by mosen**
(WORK IN PROGRESS, DO NOT MERGE) Upgrade/Migrate structure and configuration to Operator SDK v1.2 according to https://sdk.operatorframework.io/docs/building-operators/golang/migration/

### CODE REVIEW

**Comment by mosen** [comment]
still needs reorganisation of pkg/ and kustomize to fit the operator sdk 1.2 requirements

**Comment by ricardomaraschini** [comment]
@mosen what is the current status of this?

**Comment by mosen** [comment]
> @mosen what is the current status of this?

Needs a rebase on top of the existing commits. It was functional

**Comment by ricardomaraschini** [comment]
@mosen Could you please rebase and retitle the PR appropriately? I would like to take a look at it.

**Comment by mosen** [comment]
Yep sorry need to find time on weekend to rebase, give me 2 days

**Comment by mosen** [comment]
28 days ago hah, sorry work has been unrelenting. I still intend to look at this.

**Comment by mosen** [comment]
I took a look, and rebasing the conflicts is much harder than taking the existing codebase and re-applying the methodology that i used to achieve the upgrade (just go.mod was a total mess from the outset). What i will do is create a new branch from master and attempt to apply the same set of operations.

**Comment by mosen** [comment]
github.com/redhat-cop/operator-utils dependency made this PR redundant. Closing

**Pull request closed without merging**
