### PR TITLE
Rename labels to avoid conflicts

### PR DESCRIPTION
**Pull request by sabre1041**
Rename labels to avoid conflicts with other operators to resolve [PROJQUAY-2984](https://issues.redhat.com/browse/PROJQUAY-2984)

### CODE REVIEW

**Comment by flavianmissi** [comment]
is there a risk of customers relying on QBO to contain the `control-plane: controller-manager` label?

**Comment by sabre1041** [comment]
@flavianmissi there should not be. those values are the defaults as part of the `operator-sdk` and in their current form actually cause a conflict since (at least from my brief testing) the OpenShift GitOps operator uses the same labels and causes the service that is stood up by QBO to reference their pods. This work avoids this issue

**Pull request merged**
