### PR TITLE
chore: Bump dependencies (PROJQUAY-4892)

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Review by HammerMeetNail — APPROVED** [review]
LGTM 👍

**Comment by dmage** [comment]
@flavianmissi @jonathankingfc please review the commit https://github.com/quay/quay-bridge-operator/pull/60/commits/1c9cd4125bc781303e5841bfbf61bb404cbfd576.
Operator logs without this commit - https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/quay_quay-bridge-operator/60/pull-ci-quay-quay-bridge-operator-master-ocp-latest-e2e/1673356275993284608/artifacts/e2e/gather-extra/artifacts/pods/oo-z8q4l_quay-bridge-operator-6b96c9dd76-ch77h_manager.log

**Comment by flavianmissi** [comment]
/lgtm

unrelated question: there are some references to 4.6 in the tests, do we need them? OCP 4.6 is EOL

**Comment by dmage** [comment]
@flavianmissi we don't; I was pleasantly surprised that everything still works on 4.6 :) We need to use 4.10 as the lower bound.

**Comment by dmage** [comment]
https://github.com/openshift/release/pull/40693 will bump minimal OCP

**Pull request merged**
